import Eraser from "../icons/Eraser";
import Multiply from "../icons/Multiply";
import { keyboardItemType } from "../types";

export const keyboardItems: Array<keyboardItemType> = [
  {
    name: "C",
    styles: "bg-opacity-20",
    action: "CLEAR",
    payload: "",
    ariaLabel: "Clear",
  },
  {
    name: "/",
    styles: "bg-opacity-20",
    action: "ADD_OPERATION",
    payload: "/",
    ariaLabel: "Divide",
  },
  {
    name: <Multiply />,
    styles: "bg-opacity-20",
    action: "ADD_OPERATION",
    payload: "*",
    ariaLabel: "Multiply",
  },
  {
    name: <Eraser />,
    styles: "bg-opacity-20",
    action: "DELETE",
    payload: "",
    ariaLabel: "Delete",
  },
  {
    name: "7",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "7",
    ariaLabel: "7",
  },
  {
    name: "8",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "8",
    ariaLabel: "8",
  },
  {
    name: "9",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "9",
    ariaLabel: "9",
  },
  {
    name: "-",
    styles: "bg-opacity-20",
    action: "ADD_OPERATION",
    payload: "-",
    ariaLabel: "Subtract",
  },
  {
    name: "4",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "4",
    ariaLabel: "4",
  },
  {
    name: "5",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "5",
    ariaLabel: "5",
  },
  {
    name: "6",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "6",
    ariaLabel: "6",
  },
  {
    name: "+",
    styles: "row-span-2 bg-opacity-20",
    action: "ADD_OPERATION",
    payload: "+",
    ariaLabel: "Add",
  },
  {
    name: "1",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "1",
    ariaLabel: "1",
  },
  {
    name: "2",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "2",
    ariaLabel: "2",
  },
  {
    name: "3",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "3",
    ariaLabel: "3",
  },

  {
    name: "0",
    styles: "bg-opacity-50",
    action: "ADD_NUMBER",
    payload: "0",
    ariaLabel: "0",
  },
  {
    name: ".",
    styles: "bg-opacity-50",
    action: "ADD_DECIMAL",
    payload: ".",
    ariaLabel: "Decimal",
  },
  {
    name: "=",
    styles: "col-span-2 bg-opacity-20",
    action: "CALCULATE",
    payload: "",
    ariaLabel: "Equals",
  },
];
